#!/bin/bash
# Installation script for Claude API Proxy

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_DIR="${INSTALL_DIR:-$HOME/.local/claude-api-proxy}"
BIN_DIR="${BIN_DIR:-$HOME/.local/bin}"

# Default configuration values
DEFAULT_TARGET_URL="http://192.168.1.100:8443"
DEFAULT_PROXY_PORT="18844"
DEFAULT_LOG_DIR="$HOME/.claude"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --target-url)
            TARGET_URL="$2"
            shift 2
            ;;
        --proxy-port)
            PROXY_PORT="$2"
            shift 2
            ;;
        --log-dir)
            LOG_DIR="$2"
            shift 2
            ;;
        --install-dir)
            INSTALL_DIR="$2"
            shift 2
            ;;
        --bin-dir)
            BIN_DIR="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --target-url URL     Target API endpoint (default: $DEFAULT_TARGET_URL)"
            echo "  --proxy-port PORT    Local proxy port (default: $DEFAULT_PROXY_PORT)"
            echo "  --log-dir DIR        Log directory (default: $DEFAULT_LOG_DIR)"
            echo "  --install-dir DIR    Installation directory (default: $HOME/.local/claude-api-proxy)"
            echo "  --bin-dir DIR        Bin directory for launcher scripts (default: $HOME/.local/bin)"
            echo "  -h, --help           Show this help message"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            echo "Use --help for usage information."
            exit 1
            ;;
    esac
done

# Set defaults if not provided
TARGET_URL="${TARGET_URL:-$DEFAULT_TARGET_URL}"
PROXY_PORT="${PROXY_PORT:-$DEFAULT_PROXY_PORT}"
LOG_DIR="${LOG_DIR:-$DEFAULT_LOG_DIR}"

echo "=== Claude API Proxy Installation ==="
echo ""

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo "Error: Node.js is required but not installed."
    echo "Please install Node.js from https://nodejs.org/"
    exit 1
fi

echo "Node.js version: $(node --version)"

# Show configuration
echo ""
echo "Configuration:"
echo "  Target URL:  $TARGET_URL"
echo "  Proxy Port:  $PROXY_PORT"
echo "  Log Dir:     $LOG_DIR"
echo "  Install Dir: $INSTALL_DIR"
echo "  Bin Dir:     $BIN_DIR"
echo ""

# Create installation directory
echo "Installing to: $INSTALL_DIR"
mkdir -p "$INSTALL_DIR"

# Copy files
echo "Copying files..."
cp -r "$SCRIPT_DIR/src" "$INSTALL_DIR/"
cp "$SCRIPT_DIR/start.sh" "$INSTALL_DIR/"
cp "$SCRIPT_DIR/stop.sh" "$INSTALL_DIR/"
cp "$SCRIPT_DIR/package.json" "$INSTALL_DIR/"

# Create .env file with provided configuration
cat > "$INSTALL_DIR/.env" << EOF
# Claude API Proxy Configuration
# Generated by install.sh

# Target API endpoint (your custom API server)
TARGET_URL=$TARGET_URL

# Local proxy port
PROXY_PORT=$PROXY_PORT

# Log directory
LOG_DIR=$LOG_DIR
EOF
echo "Created .env file with configuration"

# Create bin directory
mkdir -p "$BIN_DIR"

# Create wrapper scripts
echo "Creating launcher scripts..."

cat > "$BIN_DIR/claude-proxy" << EOF
#!/bin/bash
"$INSTALL_DIR/start.sh" "\$@"
EOF
chmod +x "$BIN_DIR/claude-proxy"

cat > "$BIN_DIR/claude-proxy-stop" << EOF
#!/bin/bash
"$INSTALL_DIR/stop.sh" "\$@"
EOF
chmod +x "$BIN_DIR/claude-proxy-stop"

# Add bin to PATH if not already
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo ""
    echo "NOTE: $BIN_DIR is not in your PATH."
    echo "Add this to your ~/.bashrc or ~/.zshrc:"
    echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# Create log directory
mkdir -p "$LOG_DIR"

echo ""
echo "=== Installation Complete ==="
echo ""
echo "Quick start:"
echo "  claude-proxy              # Start the proxy"
echo "  claude-proxy-stop         # Stop the proxy"
echo ""
echo "Or use the scripts directly:"
echo "  $INSTALL_DIR/start.sh"
echo "  $INSTALL_DIR/stop.sh"
echo ""
echo "Configuration:"
echo "  Edit: $INSTALL_DIR/.env"
echo "  Logs: $LOG_DIR/claude-proxy.log"
echo ""
